# Generated by Django 3.1.6 on 2021-08-18 10:13

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('course_code', app.models.NameField(max_length=128, null=True)),
                ('course_name', app.models.NameField(max_length=128, null=True)),
                ('first_day', models.CharField(choices=[('Mon', 'Mon'), ('Tue', 'Tue'), ('Wed', 'Wed'), ('-', '-')], default='Mon', max_length=128)),
                ('second_day', models.CharField(choices=[('Thur', 'Thur'), ('Fri', 'Fri'), ('Sat', 'Sat'), ('-', '-')], default='Thur', max_length=128)),
                ('start_time', models.CharField(choices=[('8:30', '8:30'), ('10:30', '10:30'), ('12:30', '12:30'), ('14:30', '14:30'), ('16:30', '16:30')], default='8:30', max_length=128)),
                ('finish_time', models.CharField(choices=[('10:30', '10:30'), ('12:30', '12:30'), ('14:30', '14:30'), ('16:30', '16:30'), ('18:30', '18:30')], default='10:30', max_length=128)),
                ('section', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')], default='1', max_length=128)),
                ('room', models.CharField(choices=[('StEP ONLINE', 'StEP ONLINE'), ('1201', '1201'), ('1202', '1202'), ('1203', '1203'), ('1204', '1204'), ('1206', '1206'), ('1301', '1301'), ('1302', '1302'), ('1303', '1303'), ('1304', '1304'), ('1305', '1305'), ('1306', '1306'), ('1401', '1401'), ('1404', '1404'), ('1405', '1405'), ('1406', '1406'), ('2202', '2202'), ('2203', '2203'), ('2204', '2204'), ('2205', '2205'), ('2206', '2206'), ('2207', '2207'), ('2208', '2208'), ('2301', '2301'), ('2302', '2302'), ('2303', '2303'), ('2304', '2304'), ('2305', '2305'), ('2306', '2306'), ('2401', '2401'), ('2404', '2404'), ('2405', '2405'), ('2406', '2406'), ('2502', '2502'), ('2503', '2503'), ('2504', '2504'), ('2506', '2506'), ('Audi.', 'Audi.'), ('STUDIO', 'STUDIO'), ('COMLAB', 'COMLAB'), ('DEMO', 'DEMO'), ('Restaurant', 'Restaurant'), ('Bar', 'Bar'), ('Kitchen', 'Kitchen')], default='StEP ONLINE', max_length=128)),
                ('lecture_name', app.models.NameField(max_length=128, null=True)),
                ('description', models.CharField(blank=True, max_length=128, null=True)),
                ('prerequisite', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
    ]
